import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import { Inter } from "next/font/google";
import MenuIcon from "pixelarticons/svg/menu.svg";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="black">
      <body className={inter.className}>
        <div className="drawer-mobile drawer">
          <input id="drawer-toggle" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content relative flex flex-col">
            <div className="absolute inset-x-2 top-2 z-10 md:inset-x-4 md:top-4 rounded-md ring-1 overflow-hidden ring-[#ff0000]">
              <div className="navbar bg-base-100">
                <div className="navbar-start">
                  <label
                    htmlFor="drawer-toggle"
                    className="btn-ghost btn-square btn lg:hidden"
                  >
                    <MenuIcon />
                  </label>
                </div>
                <div className="navbar-center">
                  <Link href="/" className="btn-ghost btn text-xl uppercase">
                    Invaded map
                  </Link>
                </div>
                <div className="navbar-end"></div>
              </div>
            </div>
            {/*<div className="absolute inset-0">*/}
            <div id="content" className="absolute inset-0">{children}</div>
          </div>
          <div className="drawer-side">
            <label htmlFor="drawer-toggle" className="drawer-overlay"></label>
            <ul className="menu w-80 bg-base-100 p-4">
              {/*Sidebar content here*/}
              <li>
                <Link href="/map">Map</Link>
              </li>
              {/*<li><a>Sidebar Item 2</a></li>*/}
            </ul>
          </div>
        </div>
      </body>
      <Analytics />
    </html>
  );
}
