import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import MenuIcon from "pixelarticons/svg/menu.svg";
import Link from "next/link";
import localFont from "next/font/local";
import { BoxActiveClasses, BoxClasses, BoxHoverClasses } from "@/utils";
import { clsx } from "clsx";
import { ReactNode } from "react";

const sixtyfour = localFont({
  src: "../public/assets/fonts/Sixtyfour[BLED,SCAN].woff2",
  // src: "../public/assets/fonts/Sixtyfour-Normal.woff2",
  // src: "../public/assets/fonts/Glass_TTY_VT220.ttf",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" data-theme="black" className="text-base">
      <body className={sixtyfour.className}>
        <div className="drawer-mobile drawer">
          <input
            id="drawer-toggle"
            type="checkbox"
            className="drawer-toggle"
            tabIndex={-1}
          />
          <div className="drawer-content relative flex flex-col p-2">
            <div className="sticky top-2 z-10 mx-2 w-full place-self-center md:inset-x-6 md:top-5 md:w-fit">
              <div className={clsx("navbar bg-base-100", BoxClasses)}>
                <div className="navbar-start">
                  <label
                    htmlFor="drawer-toggle"
                    className="btn-ghost btn-square btn lg:hidden"
                  >
                    <MenuIcon className="h-full w-full text-primary" />
                  </label>
                </div>
                <div className="navbar-center">
                  <Link
                    href="/"
                    className="box-border border-y-2 border-transparent pt-1 text-2xl uppercase text-primary outline-none hover:border-y-2 hover:border-primary hover:font-bold focus-visible:border-y-2 focus-visible:border-primary focus-visible:font-bold active:border-dashed sm:text-4xl lg:text-5xl"
                  >
                    <h1>Invaded map</h1>
                  </Link>
                </div>
                <div className="navbar-end"></div>
              </div>
            </div>
            {/*<div className="absolute inset-0">*/}
            <div id="content" className="absolute inset-0">
              {children}
            </div>
          </div>
          <div className="drawer-side">
            <label htmlFor="drawer-toggle" className="drawer-overlay"></label>
            <ul className="menu w-80 gap-3 border-r-4 border-double border-primary bg-base-100 p-4">
              <li>
                <Link
                  href="/map"
                  className={clsx(
                    "text-primary",
                    BoxClasses,
                    BoxHoverClasses,
                    BoxActiveClasses
                  )}
                >
                  Map
                </Link>
              </li>
              <li>
                <Link
                  href="/highscores"
                  className={clsx(
                    "text-primary",
                    BoxClasses,
                    BoxHoverClasses,
                    BoxActiveClasses
                  )}
                >
                  Highscores
                </Link>
              </li>
            </ul>
          </div>
        </div>
      </body>
      <Analytics />
    </html>
  );
}
